name: Build, Test, and Release
run-name: Build-Test-Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build-test-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: Check if tag is on release branch
        run: |
          if ! git branch -r --contains ${{ github.ref }} | grep -q 'origin/release'; then
            echo "Tag is not on release branch"
            exit 1
          fi

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Build
        run: make

      - name: Run tests
        run: make test
        
      - name: Create RPM package
        run: make rpm

      - name: Get previous tag
        id: previoustag
        run: echo "PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${{ github.ref }}^)" >> $GITHUB_OUTPUT

      - name: Generate release notes
        id: release_notes
        run: |
          NOTES=$(git log ${{ steps.previoustag.outputs.PREVIOUS_TAG }}..${{ github.ref }} --pretty=format:'%h - %s (%an)')
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body: ${{ steps.release_notes.outputs.RELEASE_NOTES }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ./build/rpmbuild/RPMS/*/*.rpm
